# å¿…è¯»ï¼ï¼ï¼
# æ³¨æ„è§„åˆ™åœ¨æ»¡è¶³è‡ªå·±éœ€æ±‚æƒ…å†µä¸‹ï¼Œå°½é‡åšåˆ°ç²¾ç®€ï¼Œä¸è¦è¿‡åº¦å¤æ‚ï¼Œä»¥å…å½±å“æ€§èƒ½ã€‚
# è·‘è£¸æ ¸ç”¨æˆ·è¯·è‡ªè¡Œå»æ‰ä¸‹æ–¹æ§åˆ¶é¢æ¿æ¨¡å—çš„æ³¨é‡Šã€‚
# æœºåœºè®¢é˜…
proxy-providers:
  Airport1:
    url: "æœºåœºè®¢é˜…å¡«åˆ°è¿™é‡Œï¼Œä¸¤ç«¯å¼•å·ä¸è¦å»æ‰ï¼Œä¸è¦å¡«å†™åˆ°ä¸‹æ–¹é“¾æ¥é‡Œå»ï¼ï¼"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿

# èŠ‚ç‚¹ä¿¡æ¯
proxies:
  - {name: ç›´è¿, type: direct}

# å…¨å±€é…ç½® 
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: true
unified-delay: true
tcp-concurrent: true
# interface-name: enp6s18
log-level: warning
find-process-mode: 'off'
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

# ä¸ºé˜²æ­¢ä½¿ç”¨æ’ä»¶æœ‹å‹é‡åˆ°é¢æ¿é—®é¢˜ï¼Œæˆ‘æ³¨é‡Šæ‰äº†æ­¤æ¨¡å—ã€‚
# è·‘è£¸æ ¸æœ‹å‹è‡ªè¡Œåˆ é™¤æ³¨é‡Šå³å¯ï¼Œä½¿ç”¨nikkiä»…å†…æ ¸çš„uiè·¯å¾„æ”¹ä¸º/etc/nikki/run/ui
external-controller: 0.0.0.0:9090
secret: ""
external-ui: ui
external-ui-name: zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

# å—…æ¢
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "+.baidu.com"

# å…¥ç«™  
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

# DNSæ¨¡å—
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:private_domain,cn_domain"
    - "geosite:connectivity-check"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "time.*.com"
    - "+.market.xiaomi.com"
    - "+.lan"
    - "+.local"
    - "+.in-addr.arpa"
    - "localhost.ptlogin2.qq.com"
    - "localhost.sec.qq.com"
    - "localhost.work.weixin.qq.com"
    - "+.kasikornbank.com"
    - "+.hsbc.com.hk"
    - "+.hsbc.com"
    - "+.abchina.com"
    - "+95599.cn"
    - "+corporbank.abchina.com"
    - "+.abchina.com.cn"
    - "+ebank.abchina.com.cn"
    - "+cbank.abchina.com.cn"
    - "+ubank.abchina.com.cn"
    - "+ebank.abchina.com"
    - "+ubank.abchina.com"
    - "+cbank.abchina.com"
    - "+.bing.com"
    - "+.lefoo.cn"
    - '*.tailscale.com'
    - '*.zerotier.com'
  default-nameserver:
    - 223.5.5.5
  proxy-server-nameserver:
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
  # nameseverå°½é‡ç”¨è¿è¥å•†æä¾›çš„DNS
  nameserver:
    - 210.21.196.6
    - 116.116.116.116
    - 120.80.88.88
    - 221.5.88.88
  nameserver-policy:
    'geosite:category-ads': 'rcode://refused'
    
# å‡ºç«™ç­–ç•¥ï¼Œæ ¹æ®è‡ªå·±æƒ…å†µè°ƒæ•´æ¯ä¸ªç­–ç•¥é‡Œåˆ†ç»„æ’åºï¼Œå¢åˆ éƒ½å¯ä»¥ï¼Œæ¯”å¦‚æŠŠç¾å›½è‡ªåŠ¨æ”¾åˆ°ç¬¬ä¸€ä¸ªï¼Œæ¯”å¦‚åˆ é™¤é¦™æ¸¯æ•…è½¬ï¼Œæ³¨æ„åˆ«æ¼æ‰è¡¨æƒ…é€—å·ç­‰ã€‚
# å¦‚æœç›¸åº”åˆ†ç»„æ²¡æœ‰ç­›é€‰åˆ°å¯¹åº”çš„å›½å®¶ï¼Œè¯·æ ¹æ®è‡ªå·±èŠ‚ç‚¹åå­—è°ƒæ•´ç­›é€‰å…³é”®å­—ã€‚
# æ²¡æœ‰å†ä½¿ç”¨é”šç‚¹ï¼Œæ˜¯è€ƒè™‘å¾ˆå¤šæ–°æ‰‹ä¿®æ”¹éš¾åº¦ï¼Œè¿™æ ·æ–°æ‰‹ä¿®æ”¹æŸä¸ªåˆ†ç»„æ›´å®¹æ˜“äº›ã€‚
proxy-groups:
  #åˆ†æµç­–ç•¥
  - {name: ğŸš€ é»˜è®¤ä»£ç†, type: select, proxies: [ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ å°æ¹¾æ•…è½¬, ğŸ”¯ éŸ©å›½æ•…è½¬, ğŸ”¯ å¾·å›½æ•…è½¬, ğŸ”¯ åŠ æ‹¿å¤§æ•…è½¬, ğŸ”¯ å…¶ä»–æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ éŸ©å›½è‡ªåŠ¨, â™»ï¸ å¾·å›½è‡ªåŠ¨, â™»ï¸ åŠ æ‹¿å¤§è‡ªåŠ¨, â™»ï¸ å…¶ä»–è‡ªåŠ¨, ğŸ³ï¸â€ğŸŒˆ å…¨å±€è‡ªåŠ¨, ğŸ  å…¨å±€æ‰‹åŠ¨, ç›´è¿]}
  - {name: ğŸ“¹ YouTube, type: select, proxies: [ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ å°æ¹¾æ•…è½¬, ğŸ”¯ éŸ©å›½æ•…è½¬, ğŸ”¯ å¾·å›½æ•…è½¬, ğŸ”¯ åŠ æ‹¿å¤§æ•…è½¬, ğŸ”¯ å…¶ä»–æ•…è½¬, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ éŸ©å›½è‡ªåŠ¨, â™»ï¸ å¾·å›½è‡ªåŠ¨, â™»ï¸ åŠ æ‹¿å¤§è‡ªåŠ¨, â™»ï¸ å…¶ä»–è‡ªåŠ¨, ğŸ³ï¸â€ğŸŒˆ å…¨å±€è‡ªåŠ¨, ğŸ  å…¨å±€æ‰‹åŠ¨, ç›´è¿]}
  - {name: ğŸ€ Google, type: select, proxies: [ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ å°æ¹¾æ•…è½¬, ğŸ”¯ éŸ©å›½æ•…è½¬, ğŸ”¯ å¾·å›½æ•…è½¬, ğŸ”¯ åŠ æ‹¿å¤§æ•…è½¬, ğŸ”¯ å…¶ä»–æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ éŸ©å›½è‡ªåŠ¨, â™»ï¸ å¾·å›½è‡ªåŠ¨, â™»ï¸ åŠ æ‹¿å¤§è‡ªåŠ¨, â™»ï¸ å…¶ä»–è‡ªåŠ¨, ğŸ³ï¸â€ğŸŒˆ å…¨å±€è‡ªåŠ¨, ğŸ  å…¨å±€æ‰‹åŠ¨, ç›´è¿]}
  - {name: ğŸ¤– å›½å¤–AI, type: select, proxies: [ğŸ”¯ æ—¥æœ¬æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ å°æ¹¾æ•…è½¬, ğŸ”¯ éŸ©å›½æ•…è½¬, ğŸ”¯ å¾·å›½æ•…è½¬, ğŸ”¯ åŠ æ‹¿å¤§æ•…è½¬, ğŸ”¯ å…¶ä»–æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ éŸ©å›½è‡ªåŠ¨, â™»ï¸ å¾·å›½è‡ªåŠ¨, â™»ï¸ åŠ æ‹¿å¤§è‡ªåŠ¨, â™»ï¸ å…¶ä»–è‡ªåŠ¨, ğŸ³ï¸â€ğŸŒˆ å…¨å±€è‡ªåŠ¨, ğŸ  å…¨å±€æ‰‹åŠ¨, ç›´è¿]}
  - {name: ğŸ‘¨ğŸ¿â€ğŸ’» GitHub, type: select, proxies: [ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ å°æ¹¾æ•…è½¬, ğŸ”¯ éŸ©å›½æ•…è½¬, ğŸ”¯ å¾·å›½æ•…è½¬, ğŸ”¯ åŠ æ‹¿å¤§æ•…è½¬, ğŸ”¯ å…¶ä»–æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ éŸ©å›½è‡ªåŠ¨, â™»ï¸ å¾·å›½è‡ªåŠ¨, â™»ï¸ åŠ æ‹¿å¤§è‡ªåŠ¨, â™»ï¸ å…¶ä»–è‡ªåŠ¨, ğŸ³ï¸â€ğŸŒˆ å…¨å±€è‡ªåŠ¨, ğŸ  å…¨å±€æ‰‹åŠ¨, ç›´è¿]}
  - {name: ğŸµ TikTok, type: select, proxies: [ğŸ”¯ æ—¥æœ¬æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ å°æ¹¾æ•…è½¬, ğŸ”¯ éŸ©å›½æ•…è½¬, ğŸ”¯ å¾·å›½æ•…è½¬, ğŸ”¯ åŠ æ‹¿å¤§æ•…è½¬, ğŸ”¯ å…¶ä»–æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ éŸ©å›½è‡ªåŠ¨, â™»ï¸ å¾·å›½è‡ªåŠ¨, â™»ï¸ åŠ æ‹¿å¤§è‡ªåŠ¨, â™»ï¸ å…¶ä»–è‡ªåŠ¨, ğŸ³ï¸â€ğŸŒˆ å…¨å±€è‡ªåŠ¨, ğŸ  å…¨å±€æ‰‹åŠ¨, ç›´è¿]}
  - {name: ğŸ“² é€šè®¯ç¤¾äº¤, type: select, proxies: [ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ å°æ¹¾æ•…è½¬, ğŸ”¯ éŸ©å›½æ•…è½¬, ğŸ”¯ å¾·å›½æ•…è½¬, ğŸ”¯ åŠ æ‹¿å¤§æ•…è½¬, ğŸ”¯ å…¶ä»–æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ éŸ©å›½è‡ªåŠ¨, â™»ï¸ å¾·å›½è‡ªåŠ¨, â™»ï¸ åŠ æ‹¿å¤§è‡ªåŠ¨, â™»ï¸ å…¶ä»–è‡ªåŠ¨, ğŸ³ï¸â€ğŸŒˆ å…¨å±€è‡ªåŠ¨, ğŸ  å…¨å±€æ‰‹åŠ¨, ç›´è¿]}
  - {name: ğŸ¥ NETFLIX, type: select, proxies: [ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ å°æ¹¾æ•…è½¬, ğŸ”¯ éŸ©å›½æ•…è½¬, ğŸ”¯ å¾·å›½æ•…è½¬, ğŸ”¯ åŠ æ‹¿å¤§æ•…è½¬, ğŸ”¯ å…¶ä»–æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ éŸ©å›½è‡ªåŠ¨, â™»ï¸ å¾·å›½è‡ªåŠ¨, â™»ï¸ åŠ æ‹¿å¤§è‡ªåŠ¨, â™»ï¸ å…¶ä»–è‡ªåŠ¨, ğŸ³ï¸â€ğŸŒˆ å…¨å±€è‡ªåŠ¨, ğŸ  å…¨å±€æ‰‹åŠ¨, ç›´è¿]}
  - {name: ğŸ’¶ PayPal, type: select, proxies: [ğŸ”¯ æ—¥æœ¬æ•…è½¬, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ å°æ¹¾æ•…è½¬, ğŸ”¯ éŸ©å›½æ•…è½¬, ğŸ”¯ å¾·å›½æ•…è½¬, ğŸ”¯ åŠ æ‹¿å¤§æ•…è½¬, ğŸ”¯ å…¶ä»–æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ éŸ©å›½è‡ªåŠ¨, â™»ï¸ å¾·å›½è‡ªåŠ¨, â™»ï¸ åŠ æ‹¿å¤§è‡ªåŠ¨, â™»ï¸ å…¶ä»–è‡ªåŠ¨, ğŸ³ï¸â€ğŸŒˆ å…¨å±€è‡ªåŠ¨, ğŸ  å…¨å±€æ‰‹åŠ¨, ç›´è¿]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ğŸš€ é»˜è®¤ä»£ç†, ğŸ”¯ é¦™æ¸¯æ•…è½¬, ğŸ”¯ æ—¥æœ¬æ•…è½¬, ğŸ”¯ ç‹®åŸæ•…è½¬, ğŸ”¯ ç¾å›½æ•…è½¬, ğŸ”¯ å°æ¹¾æ•…è½¬, ğŸ”¯ éŸ©å›½æ•…è½¬, ğŸ”¯ å¾·å›½æ•…è½¬, ğŸ”¯ åŠ æ‹¿å¤§æ•…è½¬, ğŸ”¯ å…¶ä»–æ•…è½¬, â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, â™»ï¸ ç‹®åŸè‡ªåŠ¨, â™»ï¸ ç¾å›½è‡ªåŠ¨, â™»ï¸ å°æ¹¾è‡ªåŠ¨, â™»ï¸ éŸ©å›½è‡ªåŠ¨, â™»ï¸ å¾·å›½è‡ªåŠ¨, â™»ï¸ åŠ æ‹¿å¤§è‡ªåŠ¨, â™»ï¸ å…¶ä»–è‡ªåŠ¨, ğŸ³ï¸â€ğŸŒˆ å…¨å±€è‡ªåŠ¨, ğŸ  å…¨å±€æ‰‹åŠ¨, ç›´è¿]}
  #æ•…è½¬ç»„
  - {name: ğŸ”¯ é¦™æ¸¯æ•…è½¬, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: ğŸ”¯ æ—¥æœ¬æ•…è½¬, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$" }
  - {name: ğŸ”¯ ç‹®åŸæ•…è½¬, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore))^((?!(æ¸¯|å°|éŸ©|æ—¥|ç¾)).)*$" }
  - {name: ğŸ”¯ ç¾å›½æ•…è½¬, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(å¹¿ç¾|ç¾|US|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ‹‰æ–¯|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|(?i)States|America))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$"}
  - {name: ğŸ”¯ å°æ¹¾æ•…è½¬, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TaiWan|Taiwan)).*$"}
  - {name: ğŸ”¯ éŸ©å›½æ•…è½¬, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea)).*$"}
  - {name: ğŸ”¯ å¾·å›½æ•…è½¬, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(å¾·å›½|å¾·|DE|GER|Germany|Deutsch|Deutschland|de)).*$"}
  - {name: ğŸ”¯ åŠ æ‹¿å¤§æ•…è½¬, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(åŠ æ‹¿å¤§|CA|ca|CA|Canada)).*$"}
  - {name: ğŸ”¯ å…¶ä»–æ•…è½¬, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(ç›´è¿|æ¸¯|HK|hk|Hong Kong|HongKong|hongkong|æ·±æ¸¯|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|(?<!å°¼|-)æ—¥|JP|Japan|ğŸ‡¯ğŸ‡µ|æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|å¹¿ç¾|ç¾|US|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ‹‰æ–¯|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States|å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TaiWan|Taiwan|å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea|KOR|å¾·å›½|å¾·|DE|GER|Germany|Deutsch|Deutschland|de|åŠ æ‹¿å¤§|Canada|æ¸¥å¤ªå|æ¸©å“¥å|å¡å°”åŠ é‡Œ|CA)).)*$"}

 #è‡ªåŠ¨ç»„
  - {name: â™»ï¸ é¦™æ¸¯è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ¸¯|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|æ·±|ç¾)).)*$"}
  - {name: â™»ï¸ æ—¥æœ¬è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$" }
  - {name: â™»ï¸ ç‹®åŸè‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore))^((?!(æ¸¯|å°|éŸ©|æ—¥|ç¾)).)*$" }
  - {name: â™»ï¸ ç¾å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(å¹¿ç¾|ç¾|US|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ‹‰æ–¯|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|(?i)States|America))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$"}
  - {name: â™»ï¸ å°æ¹¾è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TaiWan|Taiwan)).*$"}
  - {name: â™»ï¸ éŸ©å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea)).*$"}
  - {name: â™»ï¸ å¾·å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(å¾·å›½|å¾·|DE|GER|Germany|Deutsch|Deutschland|de)).*$"}
  - {name: â™»ï¸ åŠ æ‹¿å¤§è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(åŠ æ‹¿å¤§|CA|ca|CA|Canada)).*$"}
  - {name: â™»ï¸ å…¶ä»–è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(ç›´è¿|æ¸¯|HK|hk|Hong Kong|HongKong|hongkong|æ·±æ¸¯|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|(?<!å°¼|-)æ—¥|JP|Japan|ğŸ‡¯ğŸ‡µ|æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|å¹¿ç¾|ç¾|US|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ‹‰æ–¯|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States|å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TaiWan|Taiwan|å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea|KOR|å¾·å›½|å¾·|DE|GER|Germany|Deutsch|Deutschland|de|åŠ æ‹¿å¤§|Canada|æ¸¥å¤ªå|æ¸©å“¥å|å¡å°”åŠ é‡Œ|CA)).)*$"}

  #å…¨å±€ç»„
  - {name: ğŸ³ï¸â€ğŸŒˆ å…¨å±€è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(ç›´è¿)).)*$"}
  - {name: ğŸ  å…¨å±€æ‰‹åŠ¨, type: select, include-all: true}

# è§„åˆ™åŒ¹é…
# æ­¤è§„åˆ™éƒ¨åˆ†æ²¡æœ‰åšé˜²æ³„éœ²å¤„ç†ï¼Œå› ä¸ºå¼Šä¸¥é‡å¤§äºåˆ©ï¼
rules:
  - DOMAIN-SUFFIX,dbankcdn.com,DIRECT
  - DOMAIN-SUFFIX,hc-cdn.com,DIRECT
  - DOMAIN-SUFFIX,hicloud.com,DIRECT
  - DOMAIN-SUFFIX,huaweicloud.com,DIRECT
  - DOMAIN-SUFFIX,hwccpc.com,DIRECT
  - DOMAIN-SUFFIX,dbankcloud.cn,DIRECT
  - DOMAIN-SUFFIX,hilink.com,DIRECT
  - DOMAIN-SUFFIX,dualstack.cn,DIRECT
  - DOMAIN-SUFFIX,myhuaweicloud.cn,DIRECT
  - DOMAIN-SUFFIX,dualstack.com,DIRECT
  - DOMAIN-SUFFIX,myhuaweicloud.ccom,DIRECT
  - DOMAIN-SUFFIX,abchina.com,DIRECT
  - DOMAIN-SUFFIX,95599.cn,DIRECT
  - DOMAIN-SUFFIX,abchina.com.cn,DIRECT
  - DOMAIN,cn.bing.com,DIRECT
  - DOMAIN,kasikornbank.com,DIRECT
  - DOMAIN-SUFFIX,kasikornbank.com,DIRECT
  - DOMAIN-SUFFIX,hsbc.com.hk,DIRECT
  - DOMAIN-SUFFIX,hsbc.com,DIRECT
  - DOMAIN-SUFFIX,tailscale.com,DIRECT
  - DOMAIN-SUFFIX,zerotier.com,DIRECT
  - DOMAIN-KEYWORD,tailscale,DIRECT
  - PROCESS-NAME,tailscaled,DIRECT
  - DOMAIN-SUFFIX,zoho.com,DIRECT
  - DOMAIN-SUFFIX,longmerchant-in.com,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR,10.147.0.0/16,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR6,fd7a:115c:a1e0::/48,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - IP-CIDR6,fc00::/7,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - RULE-SET,private_ip,ç›´è¿
  - RULE-SET,private_domain,ç›´è¿
  - DOMAIN-SUFFIX,copilot.microsoft.com,ğŸ¤– å›½å¤–AI
  - DOMAIN-SUFFIX,edgeservices.bing.com,ğŸ¤– å›½å¤–AI
  - DOMAIN-SUFFIX,sentry.io,ğŸ¤– å›½å¤–AI
  - DOMAIN-SUFFIX,intercom.io,ğŸ¤– å›½å¤–AI
  - DOMAIN-SUFFIX,qichiyu.com,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,proxylite,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,ai,ğŸ¤– å›½å¤–AI
  - RULE-SET,github_domain,ğŸ‘¨ğŸ¿â€ğŸ’» GitHub
  - RULE-SET,youtube_domain,ğŸ“¹ YouTube
  - RULE-SET,googlefcm,ğŸ€ Google
  - RULE-SET,google_domain,ğŸ€ Google
  - RULE-SET,microsoft@cn,ç›´è¿
  - RULE-SET,apple_domain,ç›´è¿
  - RULE-SET,tiktok_domain,ğŸµ TikTok
  - RULE-SET,telegram_domain,ğŸ“² é€šè®¯ç¤¾äº¤
  - RULE-SET,communication_domain,ğŸ“² é€šè®¯ç¤¾äº¤
  - RULE-SET,media_domain,ğŸ“² é€šè®¯ç¤¾äº¤
  - RULE-SET,netflix_domain,ğŸ¥ NETFLIX
  - RULE-SET,paypal_domain,ğŸ’¶ PayPal
  - RULE-SET,apple_ip,ç›´è¿,no-resolve
  - RULE-SET,google_ip,ğŸ€ Google,no-resolve
  - RULE-SET,netflix_ip,ğŸ¥ NETFLIX,no-resolve
  - RULE-SET,telegram_ip,ğŸ“² é€šè®¯ç¤¾äº¤,no-resolve
  - RULE-SET,geolocation-!cn,ğŸš€ é»˜è®¤ä»£ç†
  - RULE-SET,cn_domain,ç›´è¿
  - RULE-SET,geolocation-cn,ç›´è¿
  - RULE-SET,cn_ip,ç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

# è§„åˆ™é›†
## typeï¼šå¯é€‰http/file/inline  behaviorï¼šå¯é€‰domain/ipcidr/classical formatï¼šå¯é€‰yaml/text/mrs
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  proxylite: { <<: *class, url: "https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/main/proxy.list"}
  ai: {  <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-!cn.mrs" }
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  googlefcm: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/googlefcm.mrs"}
  microsoft@cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft@cn.mrs"}
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs"}
  speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  tiktok_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  communication_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-communication.mrs"}
  media_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-social-media-!cn.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  geolocation-cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  
  private_ip: {<<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/private.mrs"}
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  apple_ip: {<<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/apple.mrs"}
